# Generated by Django 4.2.3 on 2023-12-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='mobile',
            new_name='mobileno',
        ),
    ]
