# Generated by Django 4.2.3 on 2023-12-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
